#!/usr/bin/env node
/**
 * Installer for the MediaGrab native messaging host (macOS / Windows / Linux).
 *
 *   node native-host/install.js
 *
 * What it does (no admin rights needed):
 *   1. Derives the extension ID from extension/manifest.json's "key".
 *   2. Writes a launcher into a USER-WRITABLE dir (~/.mediagrab) — works even
 *      when the app itself is in a read-only location (Applications / Program Files).
 *      The launcher execs THIS node on mediagrab-host.mjs.
 *   3. Registers the host manifest:
 *        - macOS/Linux: a JSON file in each browser's NativeMessagingHosts dir.
 *        - Windows: a JSON file in ~/.mediagrab + an HKCU registry value per browser.
 *   4. Ensures ~/.mediagrab exists (the server writes capture-token there).
 *
 * Re-run after moving the app or changing the manifest key.
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import crypto from 'crypto';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const HOST_NAME = 'com.mediagrab.host';
const isWin = process.platform === 'win32';
const home = os.homedir();
const userDir = path.join(home, '.mediagrab');
fs.mkdirSync(userDir, { recursive: true });

// ── 1. extension ID from manifest "key" ─────────────────────────────────────
function computeExtensionId(keyB64) {
  const hash = crypto.createHash('sha256').update(Buffer.from(keyB64, 'base64')).digest();
  let id = '';
  for (let i = 0; i < 16; i++) {
    id += String.fromCharCode(97 + (hash[i] >> 4));
    id += String.fromCharCode(97 + (hash[i] & 0x0f));
  }
  return id;
}

const extManifest = JSON.parse(fs.readFileSync(path.join(repoRoot, 'extension', 'manifest.json'), 'utf-8'));
if (!extManifest.key) {
  console.error('✗ extension/manifest.json has no "key" — cannot derive a stable extension ID.');
  process.exit(1);
}
const extensionId = computeExtensionId(extManifest.key);
const allowedOrigin = `chrome-extension://${extensionId}/`;
const hostScript = path.join(__dirname, 'mediagrab-host.mjs');
const nodeExe = process.execPath;   // the node running this installer (bundled or system)

// ── 2. launcher into a user-writable dir ────────────────────────────────────
let launcherPath;
if (isWin) {
  launcherPath = path.join(userDir, 'run-host.bat');
  fs.writeFileSync(launcherPath,
    `@echo off\r\n"${nodeExe}" "${hostScript}" %*\r\n`);
} else {
  launcherPath = path.join(userDir, 'run-host.sh');
  fs.writeFileSync(launcherPath,
    `#!/bin/sh\n# Auto-generated by install.js — launches the MediaGrab native host.\nexec "${nodeExe}" "${hostScript}" "$@"\n`,
    { mode: 0o755 });
  fs.chmodSync(launcherPath, 0o755);
}

const hostManifest = {
  name: HOST_NAME,
  description: 'MediaGrab capture bridge',
  path: launcherPath,
  type: 'stdio',
  allowed_origins: [allowedOrigin],
};

// ── 3. register the host manifest per browser ───────────────────────────────
const installedTo = [];

if (isWin) {
  // Windows: write the manifest to a stable file + point HKCU registry at it.
  const manifestPath = path.join(userDir, `${HOST_NAME}.json`);
  fs.writeFileSync(manifestPath, JSON.stringify(hostManifest, null, 2));
  const regBases = {
    Chrome: 'HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts',
    Edge: 'HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts',
    Brave: 'HKCU\\Software\\BraveSoftware\\Brave-Browser\\NativeMessagingHosts',
  };
  for (const [name, base] of Object.entries(regBases)) {
    try {
      execSync(`reg add "${base}\\${HOST_NAME}" /ve /t REG_SZ /d "${manifestPath}" /f`, { stdio: 'ignore' });
      installedTo.push(name);
    } catch { /* browser not present / reg unavailable */ }
  }
} else {
  const appSup = path.join(home, 'Library', 'Application Support');
  const linuxCfg = path.join(home, '.config');
  const targets = process.platform === 'darwin'
    ? [
        ['Chrome',   path.join(appSup, 'Google/Chrome/NativeMessagingHosts')],
        ['Chromium', path.join(appSup, 'Chromium/NativeMessagingHosts')],
        ['Edge',     path.join(appSup, 'Microsoft Edge/NativeMessagingHosts')],
        ['Brave',    path.join(appSup, 'BraveSoftware/Brave-Browser/NativeMessagingHosts')],
      ]
    : [
        ['Chrome',   path.join(linuxCfg, 'google-chrome/NativeMessagingHosts')],
        ['Chromium', path.join(linuxCfg, 'chromium/NativeMessagingHosts')],
        ['Edge',     path.join(linuxCfg, 'microsoft-edge/NativeMessagingHosts')],
        ['Brave',    path.join(linuxCfg, 'BraveSoftware/Brave-Browser/NativeMessagingHosts')],
      ];
  for (const [name, dir] of targets) {
    if (!fs.existsSync(path.dirname(dir))) continue;   // browser not installed
    try {
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${HOST_NAME}.json`), JSON.stringify(hostManifest, null, 2));
      installedTo.push(name);
    } catch (e) { console.error(`  ! ${name}: ${e.message}`); }
  }
}

// ── report ──────────────────────────────────────────────────────────────────
console.log('MediaGrab native host installed.\n');
console.log('  Extension ID : ' + extensionId);
console.log('  Launcher     : ' + launcherPath);
console.log('  Node         : ' + nodeExe);
console.log('  Registered   : ' + (installedTo.join(', ') || '(no Chromium-family browser found)'));
console.log('\nNext steps:');
console.log('  1. Open the MediaGrab app (starts the local server on :9800).');
console.log('  2. Load the extension at chrome://extensions (Developer mode → Load unpacked →');
console.log('     select the extension/ folder). Confirm the ID matches the one above.');
console.log('  3. On a course/streaming page: MediaGrab toolbar icon → enable → play → download.');
if (!installedTo.length) console.log('\n⚠ No browser found to register — open your browser once, then re-run.');
